### ISSUE TITLE
[DTM-08] Add option for circle server buttons or square server buttons

### ISSUE THREAD

**Issue by bit-whisperer** [XYZenix/XYZenixThemes#114]
The most jarring change from the old v1 and v2 themes was the fact the buttons are now square. I noticed the circle buttons play nicer with some elements of discord like server folders. Is there a way to make separate "flavors" of the v2 theme for square and circle buttons?

Thanks

**Comment by bit-whisperer** [comment]
I ended up making the change myself. Removing lines 626 - 629 added the OG button shapes back on the guilds list. In the event the location changes, the code is shown below:
```
.scroller__3d071 .wrapper__3af0b foreignObject {
  mask: none !important;
  -webkit-mask: none !important;
}

**Comment by XYZenix** [comment]
sorry, i forgot to look at this issue earlier
```css
.scroller__3d071 .wrapper_d281dd img, .scroller__3d071 .wrapper_d281dd,
.scroller__3d071 .wrapper_d281dd .childWrapper__01b9c.acronym_cd4809,
.scroller__3d071 .tutorialContainer__890ea + .listItem_fa7b36 .wrapper_d281dd .childWrapper__01b9c,
.scroller__3d071 .circleIconButton_d8df29,
.scroller__3d071 :is(.folder__17546, .folderIconWrapper__72239) .guildIcon__2e5ab.iconSizeSmol__7ee47 {
  border-radius: 64px;
}
.scroller__3d071 :is(.folder__17546, .folderIconWrapper__72239) {
  border-radius: 14px;
}
```
this should work without the changes you made (hopefully it also didn't break anything)
i'll figure out how to incorporate an option for this into the theme at some point
