### ISSUE TITLE
[Contribution] Old Reactions CSS

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/XYZenixThemes#17]
```css
.reaction-1hd86g {
    border-radius: .25rem;
    cursor: pointer;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    -ms-flex-negative: 0;
    flex-shrink: 0;
    margin-right: .125rem;
    margin-bottom: .125rem;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-transition: background-color .1s ease;
    transition: background-color .1s ease;
    background: var(--background-modifier-accent);
}
.reactionInner-15NvIl {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    padding: 0 .375rem;
}
.reactions-12N0jA {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-flex: 1;
    -ms-flex: 1 0 auto;
    flex: 1 0 auto;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-bottom: -.25rem;
    padding-bottom: .125rem;
}
.reactionCount-2mvXRV {
    font-size: 0.875rem;
    font-weight: 500;
    margin-left: .375rem;
    text-align: center;
    color: var(--text-muted);
}
.reaction-1hd86g.reactionMe-wv5HKu {
    background-color: rgba(114,137,218,.3);
    border-color: rgba(0, 0, 0, 0)
}
.reactionMe-wv5HKu .reactionCount-2mvXRV, .reactionMe-wv5HKu:hover .reactionCount-2mvXRV {
    color: #7289da !important;
}
.reaction-1hd86g:hover {
     background: var(--background-modifier-accent);
    border-color: rgba(0, 0, 0, 0)
}
```
